name: Publish package to PyPI

on:
    release:
        types: [created]

jobs:
    build:
      strategy:
      matrix:
          os: [windows-latest, ubuntu-latest]
          py-version: [3.8, 3.9]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setting up Python ${{ matrix.py-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.py-version }}
            - name: Install dependencies
              run: |
                  python -m install --upgrade pip
                  pip install black setuptools wheel twine
                  if [-f requirements.txt]; then pip install -r requirements.txt; fi
            - name: Lint code with black
              run: black . --line-length 88

    publish:
      strategy:
      matrix:
          os: [windows-latest, linux-latest]
          py-version: [3.8, 3.9]

        runs-on: ${{ matrix.os }}
        needs: [build]
        steps:
            - name: Building package
              run: python setup.py bdist_wheel sdist
            - name: Publishing to PyPI
              run: twine upload dist/*
              env:
                  TWINE_USERNAME: ${{secrets.PYPI_LOGIN}}
                  TWINE_PASSWORD: ${{secrets.PYPI_PASSWORD}}
