name: Publish package to PyPI

on: [push]

jobs:
    build:
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest]
                py-version: [3.8, 3.9]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Setting up Python ${{ matrix.py-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.py-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install black
                  if ([-f requirements.txt]); then pip install -r requirements.txt; fi
            - name: Lint code with black
              run: black . --line-length 88
